import streamlit as st
import google.generativeai as genai
import os
import re

# Configuração da página
st.set_page_config(page_title="Fábrica do Luiz", page_icon="🏗️", layout="wide")

# --- FUNÇÕES AUXILIARES ---
def limpar_codigo(texto):
    """Extrai apenas o código Python de dentro de blocos Markdown, se houver."""
        # O padrão procura por blocos que começam com ```python e terminam com ```
            padrao = r"```python(.*?)```"
                match = re.search(padrao, texto, re.DOTALL)
                    if match:
                            return match.group(1).strip()
                                # Se não houver formatação markdown, tenta retornar o texto original limpo
                                    return texto.replace("```", "").strip()

                                    # --- CONFIGURAÇÃO DA CHAVE ---
                                    # Busca a chave de API nos Secrets do Streamlit ou variáveis de ambiente
                                    if 'GEMINI_API_KEY' in st.secrets:
                                        minha_chave = st.secrets['GEMINI_API_KEY']
                                        else:
                                            minha_chave = os.environ.get('GEMINI_API_KEY')

                                            # --- INTERFACE PRINCIPAL ---
                                            st.title("🏗️ FÁBRICA DO LUIZ")
                                            st.subheader("Orquestrador de Software com IA Nativa")
                                            st.markdown("""
                                            Esta fábrica gera código Python **pronto para uso** para novos aplicativos Streamlit.
                                            O código gerado já inclui:
                                            - 🧠 Integração com Gemini
                                            - 💬 Interface de Chat com Histórico (Memória)
                                            - 🔑 Gestão inteligente de API Key
                                            """)
                                            st.write("---")

                                            # Verificação de segurança da chave da Fábrica
                                            if not minha_chave:
                                                st.error("🔐 ERRO NA FÁBRICA: Configure a GEMINI_API_KEY para a fábrica funcionar.")
                                                    st.info("Dica: Vá em Settings > Secrets no seu Dashboard do Streamlit ou use o arquivo secrets.toml.")
                                                        st.stop()

                                                        # Configura o motor da Fábrica
                                                        genai.configure(api_key=minha_chave)
                                                        motor = genai.GenerativeModel('gemini-1.5-flash')

                                                        # Área de Entrada
                                                        col1, col2 = st.columns([2, 1])

                                                        with col1:
                                                            missao = st.text_area("O que este novo aplicativo deve fazer?", 
                                                                                    placeholder="Ex: Um assistente de estudo que cria quizzes sobre Biologia...",
                                                                                                            height=150)

                                                                                                            with col2:
                                                                                                                st.write("### Parâmetros")
                                                                                                                    criatividade = st.slider("Nível de Criatividade do Código", 0.0, 1.0, 0.7)
                                                                                                                        st.write(" ")
                                                                                                                            btn_fabricar = st.button("🚀 FABRICAR AGORA", type="primary", use_container_width=True)

                                                                                                                            # Lógica de Geração
                                                                                                                            if btn_fabricar:
                                                                                                                                if not missao:
                                                                                                                                        st.warning("⚠️ Por favor, descreva a missão do app primeiro.")
                                                                                                                                            else:
                                                                                                                                                    with st.spinner("🤖 Arquitetando solução, escrevendo código e depurando..."):
                                                                                                                                                                try:
                                                                                                                                                                                # Instrução técnica para a IA gerar o código correto
                                                                                                                                                                                                instrucao = f"""
                                                                                                                                                                                                                Atue como um Especialista em Streamlit e Python.
                                                                                                                                                                                                                                Sua tarefa é escrever um script Python ÚNICO E EXECUTÁVEL para a seguinte missão: "{missao}".

                                                                                                                                                                                                                                                REQUISITOS OBRIGATÓRIOS DO CÓDIGO GERADO:
                                                                                                                                                                                                                                                                1. Imports: `streamlit`, `google.generativeai`, `os`.
                                                                                                                                                                                                                                                                                2. Configuração da API Key (CRÍTICO): 
                                                                                                                                                                                                                                                                                                   - Tente ler `st.secrets["GEMINI_API_KEY"]`.
                                                                                                                                                                                                                                                                                                                      - Se falhar, use `st.sidebar.text_input` para pedir a chave ao usuário.
                                                                                                                                                                                                                                                                                                                                         - Se não houver chave configurada, use st.info("Insira a chave na lateral") e st.stop().
                                                                                                                                                                                                                                                                                                                                                         3. Chat e Memória:
                                                                                                                                                                                                                                                                                                                                                                            - Use `st.session_state` para armazenar o histórico (mensagens).
                                                                                                                                                                                                                                                                                                                                                                                               - Exiba as mensagens usando `st.chat_message`.
                                                                                                                                                                                                                                                                                                                                                                                                               4. Modelo: Use `gemini-1.5-flash`.
                                                                                                                                                                                                                                                                                                                                                                                                                               5. NÃO inclua explicações fora do código, responda apenas com o bloco de código Python formatado.
                                                                                                                                                                                                                                                                                                                                                                                                                                               """
                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               resposta = motor.generate_content(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   instrucao,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       generation_config=genai.types.GenerationConfig(temperature=criatividade)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       codigo_bruto = resposta.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       codigo_limpo = limpar_codigo(codigo_bruto)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       st.success("✅ Aplicativo Fabricado com Sucesso!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # Exibição do resultado
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       tab1, tab2 = st.tabs(["📄 Código Fonte", "💾 Download"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       with tab1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           st.code(codigo_limpo, language='python')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           with tab2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               st.write("Salve o arquivo como `app.py` e execute localmente.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   st.download_button(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           label="📥 Baixar arquivo .py",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   data=codigo_limpo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           file_name="meu_app_gerado.py",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   mime="text/x-python"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   st.error(f"💥 Ocorreu um erro na linha de montagem: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   st.write("---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   st.caption("Fábrica do Luiz | Monitoramento Estratégico Abril 2026")